name: Generate sitemap
on: [push]
jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: 'https://asrcomp.github.io/'
    - name: Commit & push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add sitemap.xml
        git commit -m 'Update sitemap' || exit 0
        git push
